name: molitav
description: "An aplication for capturing and monitoring user health condition by using five parameters: Heart Rate, SPO2, Body Temperature, Skin Temperature, and Respiration."
publish_to: 'none'
version: 2.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  meta: ^1.12.0
  permission_handler: ^12.0.1
  provider: ^6.1.2
  restart_app: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: assets/logo/splash.png
  color: "#1E6EB0"
  android_12:
    image: assets/logo/splash.png
    color: "#1E6EB0"
    
fonts:
  - family:
    fonts:
      - asset: assets/fonts/Roboto-Light.ttf
        weight: 300
      - asset: assets/fonts/Roboto-Regular.ttf
        weight: 400        
      - asset: assets/fonts/Roboto-Bold.ttf
        weight: 700